### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error

### ISSUE THREAD

**Issue by sourabh-patil** [PrithivirajDamodaran/FlashRank#11]
Hey, Thanks for the great work! I have been using flashrank since few days. It worked fine but currently I am getting following error.

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/flashrank/ms-marco-MiniLM-L-12-v2.zip

I tried to use different versions of rerankers given by you. Changed the network also, but still getting this issue. Any leads to troubleshoot it?

**Comment by tomcotter7** [comment]
what version of the library are you running? I updated to `v0.1.69` and it solved this issue.

**Comment by sourabh-patil** [comment]
0.1.66

**Comment by sourabh-patil** [comment]
Yes. Works with new version. Thanks!
