### ISSUE TITLE
Initializing Ranker not working

### ISSUE THREAD

**Issue by kingsene19** [PrithivirajDamodaran/FlashRank#12]
Hi there, I noticed that there was a change in the Config.py to the model url to **https://storage.googleapis.com/flash-rank**
However when initializing a Ranker, it tries to retrieve the model from **https://storage.googleapis.com/flashrank** which causes a 403 forbidden.

Kind regards.

```bash
HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/flashrank/ms-marco-TinyBERT-L-2-v2.zip
```

Here is the following error

**Comment by PrithivirajDamodaran** [comment]
https://github.com/PrithivirajDamodaran/FlashRank/issues/11
