### ISSUE TITLE
I am having issue while initializing Reranker

### ISSUE THREAD

**Issue by abhigrazitti** [PrithivirajDamodaran/FlashRank#16]
```
ranker = Ranker()
rerankrequest = RerankRequest(query=query, passages=initial_docs)
reordered_docs = ranker.rerank(rerankrequest)

```

ERROR:__main__:Error processing query: [WinError 2] The system cannot find the file specified: '\\opt'

**Comment by PrithivirajDamodaran** [comment]
Please share additional details on the OS you are installing etc ?

**Comment by Eknathabhiram** [comment]
@abhigrazitti 
ERROR:main:Error processing query: [WinError 2] The system cannot find the file specified: '\opt'.

You can try changing your destination folder to your working directory, your model will be saved there itself.

use ranker = Ranker(cache_dir="your working directory")
