### ISSUE TITLE
How to deploy a FlashRank Reranker model on AWS LAMBDA as specified?

### ISSUE THREAD

**Issue by NeevrajKB** [PrithivirajDamodaran/FlashRank#20]

**Comment by NeevrajKB** [comment]
Hi!
I'm Neevraj,
Looking to deploy a reranking model using FlashRank, you mentioned Lowest $ on AWS Lambda, so was wondering how I could deploy a model on it using your framework. Also how could I contribute to the supported models?
Thanks!

**Comment by PrithivirajDamodaran** [comment]
How are you writing your lambda handler ? are you using frameworks like [serverless.com](https://www.serverless.com/framework/docs-providers-aws-guide-functions) ?, You should be able to write AWS lambda handlers as HTTP /POST or /GET for interactive serving and with Say AWS Queues for batch serving on your own. The scope of the deployment patterns is only to guide you on best pratices like loading a model / where to keep your models on startup and serve it.
