### ISSUE TITLE
Support BAAI/bge-reranker-base?

### ISSUE THREAD

**Issue by vipinap98** [PrithivirajDamodaran/FlashRank#23]
Wont it be good if we have support for BAAI/bge-reranker-base model? seems it works pretty well

**Comment by PrithivirajDamodaran** [comment]
No, flashrank philosophy is choose mini / tiny models. So for pointwise ranking with cross-encoder based models > 1 GB (like BAAI/bge-reranker-base) are doesnt make sense. For LLM listwise ranking using LLMs its a different criteria.
