### ISSUE TITLE
ResourceWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by sudhanshu746** [PrithivirajDamodaran/FlashRank#25]
tokens_map = json.load(open(str(self.model_dir / "special_tokens_map.json")
You have opened  special token file, used it, but then forgot to close the file. 

when Python closes it for you when it notices that the file object is dead, but this only occurs after some unknown time has elapsed. Thus in recent versions, Python also prints a ResourceWarning when it does that.

**Comment by albertauyeung** [comment]
I think this issue is fixed in the main branch now. @PrithivirajDamodaran will there be a new release soon?

**Comment by PrithivirajDamodaran** [comment]
Done !
