### ISSUE TITLE
llama-cpp-python dependency not needed?

### ISSUE THREAD

**Issue by JarbasAl** [PrithivirajDamodaran/FlashRank#29]
why is it a dependency on setup.py? I do not see it used by the package, am I missing something?

when i installed flashrank it downgraded my llama-cpp-python version, this blocks me from using this package, specially given with how fast llama.cpp changes. 

My main concern is that for GPU support i need to install llama-cpp-python with ` CMAKE_ARGS="-DGGML_CUDA=on" FORCE_CMAKE=1 pip install llama-cpp-python --force-reinstall --no-cache-dir`, and simply installing flashrank undoes this, immediately making this package unsuitable for usage with LLMs (which is the main use case)

**Comment by PrithivirajDamodaran** [comment]
Yes ! you are missing something, it is required for listwise reranking based on LLMs. Hence conditionally imported. 

I haven't seen a need for separating the req. if listwise ranking is something you would not need we can have conditional installs say flashrank[pairwise] which would only give you pairwise rankers (CE based models only). 

State your request in this thread.

**Comment by JarbasAl** [comment]
I see now it is needed for the zephyr model, i missed that earlier

To clarify my issue, in the same project where i want to introduce flashrank i already have llama-cpp-python installed for usage with an LLM, so when i install flashrank it downgrades and reinstalls that package. and when doing this i lose the GPU support because of the downgrade (the wheel on pypi is cpu only). 

What this means for me is that even if i dont use the zephyr model from flashrank, i can't add flashrank to my requirements.txt because installing flashrank in the first place is what causes issues for me

So my request would be that we move llama-cpp-python into extra requirements (`extras_require` in setup.py), since most models only need onnxruntime there is no need for llama-cpp-python in most use cases, also making the install lighter for those not using the zephyr model

eg,  `pip install flashrank[llama]` would also have the llama-cpp-python dependency, while `pip install flashrank` would not install llama

> Note: Using with LLMs is not at all the main use case for Flashrank

i meant it was my main use case, sorry for not being clear :sweat_smile:

**Comment by curiousily** [comment]
Hi @PrithivirajDamodaran,

I'm trying to deploy a Streamlit app and the build fails because of the `llama-cpp-python` library dependency. Making it an optional dependency solves this (it is quite a heavy library with different options - CPU/GPU settings etc) and makes flashrank really lite.

Thank you for making such an awesome library!

**Comment by PrithivirajDamodaran** [comment]
Thank you ! That was actually my proposal, (if you had read my comment). 

Sure will get to it. Once done will update here.

**Comment by PrithivirajDamodaran** [comment]
Done, upgrade to v0.2.8

See readme for more details.
