### ISSUE TITLE
Update `README.md` to mention any models trained on copyrighted data

### ISSUE THREAD

**Issue by chrispy-snps** [PrithivirajDamodaran/FlashRank#7]
This is an enhancement request.

Could you please update the `README.md` file to indicate whether any of the models were trained on copyrighted data, and if so, which ones? Thanks!

**Comment by PrithivirajDamodaran** [comment]
**Out of scope:** As readme states Flashrank brings existing SoTA ranking models Fx cross encoders for optimal reranking, it doesn't train or own models. Original Model owners of each model have written detailed model cards for all the models in huggingface. Look it up and / or contact the model owners.
